name: Build and Push to ECR

on:
  push:
    branches:
      - v2-eks

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: |
          docker build -t flask-app ./app

      - name: Tag Image
        run: |
          docker tag flask-app:latest \
            502411382579.dkr.ecr.ap-south-2.amazonaws.com/flask-app:latest
          docker tag flask-app:latest \
            502411382579.dkr.ecr.ap-south-2.amazonaws.com/flask-app:${{ github.sha }}

      - name: Push to ECR
        run: |
          docker push 502411382579.dkr.ecr.ap-south-2.amazonaws.com/flask-app:latest
          docker push 502411382579.dkr.ecr.ap-south-2.amazonaws.com/flask-app:${{ github.sha }}

      - name: Print Image URI
        run: |
          echo "Image pushed: 502411382579.dkr.ecr.ap-south-2.amazonaws.com/flask-app:${{ github.sha }}"